### PR TITLE
Updated golang.zx2c4.com/wireguard Fixes #57

### LINKED ISSUE #57: Error building cli/encore from source in windows 10.
1. When I am building encore cli in windows, getting compilation error `..\..\daemon\dash\server.go:25:12: pattern dashapp/dist/*: no matching files found`

encore-error

So to compile this, I have removed this line https://github.com/encoredev/encore/blob/67aefe20466f686561c300dd1b8d6276a563b2bc/cli/daemon/dash/server.go#L25

2. After it compiles, then when I run `./encore.exe -h` it panics.
encore-panic

This seems issue in wireguard/windows dependency. So after I update wireguard from v0.3.1 to v0.4, it works. But I feel like this can have impact somewhere else as well.
encore-mod

Please let me know what will be the permanent solution for both the issues, and if upgrading wireguard is only solution then I will pull request for it.

Thanks.

### PR DESCRIPTION
**Pull request by frzam**
Please refer https://github.com/encoredev/encore/issues/57

### CODE REVIEW

**Comment by frzam** [comment]
Windows build:
win-build
Linux build:
linux-build

**Comment by eandre** [comment]
Thank you!
