### ISSUE TITLE
Error building cli/encore from source in windows 10.

### ISSUE THREAD

**Issue by frzam** [encoredev/encore#57]
1. When I am building encore cli in windows, getting compilation error `..\..\daemon\dash\server.go:25:12: pattern dashapp/dist/*: no matching files found`

<img width="708" alt="encore-error" src="https://user-images.githubusercontent.com/22986964/129436515-2882e6aa-3c6c-44f4-bebd-e56d662b7149.PNG">

So to compile this, I have removed this line https://github.com/encoredev/encore/blob/67aefe20466f686561c300dd1b8d6276a563b2bc/cli/daemon/dash/server.go#L25

2. After it compiles, then when I run `./encore.exe -h` it panics.
<img width="669" alt="encore-panic" src="https://user-images.githubusercontent.com/22986964/129437330-9872ad19-9726-40fd-bb3f-a73171847c10.PNG">

This seems issue in wireguard/windows dependency. So after I update wireguard from v0.3.1 to v0.4, it works. But I feel like this can have impact somewhere else as well.
<img width="537" alt="encore-mod" src="https://user-images.githubusercontent.com/22986964/129437460-364b34fa-6e1a-4bab-b97c-e74db876a4e1.PNG">

Please let me know what will be the permanent solution for both the issues, and if upgrading wireguard is only solution then I will pull request for it.

Thanks.

**Comment by eandre** [comment]
Thanks very much @frzam! For your first issue I documented this very recently in [CONTRIBUTING.md)(https://github.com/encoredev/encore/blob/main/CONTRIBUTING.md#developing-the-development-dashboard). We should make this clearer in the instructions. (Perhaps we should commit some placeholder file so the build doesn't fail?)

As for your second issue, that's a new one. I think upgrading WireGuard is perfectly fine as a solution! Thanks very much for reporting and investigating. Want to send a PR to fix it? :)

**Comment by frzam** [comment]
Yup sure.

**Comment by frzam** [comment]
@eandre I think I missed something, on windows it is still not compiling 😔, this `golang.zx2c4.com/wireguard` also needs to updated from `v0.0.20201118` to `v0.0.0-20210728232740-bad6caeb82ed` then it complies on windows, but then on linux(and most probably mac), it is not compiling because of `conn.Bind` param in https://pkg.go.dev/golang.zx2c4.com/wireguard/device#NewDevice
I am not familiar with wireguard api, but may be we can pass something like https://pkg.go.dev/golang.zx2c4.com/wireguard@v0.0.0-20210805125648-3957e9b9dd19/conn#NewDefaultBind (Don't know the implementation) in https://github.com/encoredev/encore/blob/c8f23efd57518f312153121f56b9d2365e6f2aed/cli/internal/wgtunnel/wgtunnel_linux.go#L262  and https://github.com/encoredev/encore/blob/c8f23efd57518f312153121f56b9d2365e6f2aed/cli/internal/wgtunnel/wgtunnel_darwin.go#L282

**Comment by eandre** [comment]
Thanks @frzam. As we discussed on [Slack](https://encore.dev/slack) I believe the best path forward is to update `golang.zx2c4.com/wireguard` and use `conn.NewDefaultBind()`. Reopened this issue until we've sorted it out completely!
